
package framepackages;

import furniture.*;
import java.text.DecimalFormat;

/**
 * this class handles the user orders
 * @author eze
 */

public class DashboardFrame extends javax.swing.JFrame {

    
    //creating static variables 
    static int desks;
    static int chairs;
    static int tables;
    static double total;
    
    private static final DecimalFormat df = new DecimalFormat("0.00");
    
    //initializing the variables in constructor
    public DashboardFrame() {
        initComponents();
        desks =  0;
        chairs = 0;
        tables = 0;
        total = 0.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskButtonLabel = new javax.swing.JLabel();
        addDeskBtn = new javax.swing.JButton();
        removeDeskBtn = new javax.swing.JButton();
        numOfDesk = new javax.swing.JLabel();
        chairBtnLabel = new javax.swing.JLabel();
        removeTableBtn = new javax.swing.JButton();
        addTableBtn = new javax.swing.JButton();
        numOfChairs = new javax.swing.JLabel();
        tableBtnLabel = new javax.swing.JLabel();
        numOfTables = new javax.swing.JLabel();
        addChairBtn = new javax.swing.JButton();
        removeChairBtn = new javax.swing.JButton();
        totalPriceBtn = new javax.swing.JButton();
        totalPrice = new javax.swing.JLabel();
        clearAllBtn = new javax.swing.JButton();
        summaryBtn = new javax.swing.JButton();
        reviewOrderBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deskButtonLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        deskButtonLabel.setText(" Desk");

        addDeskBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDeskBtn.setText("+");
        addDeskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeskBtnActionPerformed(evt);
            }
        });

        removeDeskBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeDeskBtn.setText("-");
        removeDeskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDeskBtnActionPerformed(evt);
            }
        });

        numOfDesk.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numOfDesk.setText("0");

        chairBtnLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        chairBtnLabel.setText("Chair");

        removeTableBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeTableBtn.setText("-");
        removeTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTableBtnActionPerformed(evt);
            }
        });

        addTableBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addTableBtn.setText("+");
        addTableBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableBtnActionPerformed(evt);
            }
        });

        numOfChairs.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numOfChairs.setText("0");

        tableBtnLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tableBtnLabel.setText("Table");

        numOfTables.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numOfTables.setText("0");

        addChairBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addChairBtn.setText("+");
        addChairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChairBtnActionPerformed(evt);
            }
        });

        removeChairBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeChairBtn.setText("-");
        removeChairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeChairBtnActionPerformed(evt);
            }
        });

        totalPriceBtn.setText("Total Price");
        totalPriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceBtnActionPerformed(evt);
            }
        });

        totalPrice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalPrice.setText("0.0");

        clearAllBtn.setText("Clear");
        clearAllBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllBtnActionPerformed(evt);
            }
        });

        summaryBtn.setText("Summary");
        summaryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summaryBtnActionPerformed(evt);
            }
        });

        reviewOrderBtn.setText("Review Order");
        reviewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewOrderBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("      Order Dash Board ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableBtnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(removeTableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chairBtnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addChairBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(removeChairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(totalPriceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addDeskBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(removeDeskBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearAllBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deskButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(summaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reviewOrderBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(numOfDesk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numOfTables, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numOfChairs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deskButtonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addDeskBtn)
                            .addComponent(removeDeskBtn))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numOfDesk, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(tableBtnLabel)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeTableBtn)
                    .addComponent(addTableBtn)
                    .addComponent(numOfTables, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(chairBtnLabel)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addChairBtn)
                    .addComponent(removeChairBtn)
                    .addComponent(numOfChairs, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPriceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearAllBtn)
                    .addComponent(summaryBtn)
                    .addComponent(reviewOrderBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDeskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeskBtnActionPerformed
       //increase number of desk by one when clicked
        numOfDesk.setText(++desks + "");
    }//GEN-LAST:event_addDeskBtnActionPerformed

    private void removeDeskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDeskBtnActionPerformed
        //reduce number of desk by one when clicked
        numOfDesk.setText(--desks + "");
    }//GEN-LAST:event_removeDeskBtnActionPerformed

    private void removeTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTableBtnActionPerformed
        //reduce number of tables by one when clicked
        numOfTables.setText(--tables + "");
    }//GEN-LAST:event_removeTableBtnActionPerformed

    private void addTableBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableBtnActionPerformed
        //increase number of tables by one when clicked
        numOfTables.setText(++tables + "");
    }//GEN-LAST:event_addTableBtnActionPerformed

    private void addChairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChairBtnActionPerformed
        //increase number of chairs by one when clicked
        numOfChairs.setText(++chairs + "");
    }//GEN-LAST:event_addChairBtnActionPerformed

    private void removeChairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeChairBtnActionPerformed
        //reduce number of chairs by one when clicked
        numOfChairs.setText(--chairs + "");
    }//GEN-LAST:event_removeChairBtnActionPerformed

    /**
     * This calculates the total price of the items picked
     * @param evt 
     */
    private void totalPriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceBtnActionPerformed
        
        //initialized the objects
        Chair chair = new Chair();
        Desk  desk  = new Desk();
        Table table = new Table();
        
        total = (desks * desk.getItemPrice()) + (chairs * chair.getItemPrice()) + (tables * table.getItemPrice());
        
        totalPrice.setText(df.format(total) + "");
    }//GEN-LAST:event_totalPriceBtnActionPerformed

    /**
     * This clears all the labels to zero when the clear button
     * is clicked
     * @param evt 
     */
    private void clearAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBtnActionPerformed

        desks  = 0;
        chairs = 0;
        tables = 0;
        total = 0;
        numOfChairs.setText(chairs + "");
        numOfDesk.setText(desks + "");
        numOfTables.setText(tables + "");
        totalPrice.setText(total + "");
    }//GEN-LAST:event_clearAllBtnActionPerformed

    private void summaryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summaryBtnActionPerformed
        //calls a new frame and disposes the previous frame
        SummaryFrame frame = new SummaryFrame();
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.show();
        dispose();
    }//GEN-LAST:event_summaryBtnActionPerformed

    private void reviewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewOrderBtnActionPerformed
        //calls a new frame and disposes the previous frame
        ReviewOrderFrame frame = new ReviewOrderFrame();
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.show();
        dispose();     
    }//GEN-LAST:event_reviewOrderBtnActionPerformed


 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChairBtn;
    private javax.swing.JButton addDeskBtn;
    private javax.swing.JButton addTableBtn;
    private javax.swing.JLabel chairBtnLabel;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JLabel deskButtonLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel numOfChairs;
    private javax.swing.JLabel numOfDesk;
    private javax.swing.JLabel numOfTables;
    private javax.swing.JButton removeChairBtn;
    private javax.swing.JButton removeDeskBtn;
    private javax.swing.JButton removeTableBtn;
    private javax.swing.JButton reviewOrderBtn;
    private javax.swing.JButton summaryBtn;
    private javax.swing.JLabel tableBtnLabel;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JButton totalPriceBtn;
    // End of variables declaration//GEN-END:variables
}
